# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/art/Documents/ProgrammingStuff/RSRC_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 343)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selected_dir_label = QtWidgets.QLabel(Dialog)
        self.selected_dir_label.setObjectName("selected_dir_label")
        self.horizontalLayout.addWidget(self.selected_dir_label)
        self.selectedDirectoryTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.selectedDirectoryTextBrowser.setObjectName("selectedDirectoryTextBrowser")
        self.horizontalLayout.addWidget(self.selectedDirectoryTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chooseDirectoryButton = QtWidgets.QPushButton(Dialog)
        self.chooseDirectoryButton.setObjectName("chooseDirectoryButton")
        self.verticalLayout.addWidget(self.chooseDirectoryButton)
        self.config_options_label = QtWidgets.QLabel(Dialog)
        self.config_options_label.setObjectName("config_options_label")
        self.verticalLayout.addWidget(self.config_options_label)
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout.addWidget(self.resetButton)
        self.backupButton = QtWidgets.QPushButton(Dialog)
        self.backupButton.setObjectName("backupButton")
        self.verticalLayout.addWidget(self.backupButton)
        self.restoreButton = QtWidgets.QPushButton(Dialog)
        self.restoreButton.setObjectName("restoreButton")
        self.verticalLayout.addWidget(self.restoreButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.selected_dir_label.setText(_translate("Dialog", "Selected directory:"))
        self.chooseDirectoryButton.setText(_translate("Dialog", "Choose Directory..."))
        self.config_options_label.setText(_translate("Dialog", "Configuration Options:"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.backupButton.setText(_translate("Dialog", "Backup"))
        self.restoreButton.setText(_translate("Dialog", "Restore"))

